<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_open_in_new</name>
   <tag></tag>
   <elementGuidId>d26d76e6-b8ad-4942-b2c9-0723c762238d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='xm-main']/article[2]/app-project-list/div/article/app-table-xm/div/div/div[2]/table/tbody/tr[9]/th/div/button/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons xm-btn-editar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>open_in_new</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xm-main&quot;)/article[@class=&quot;xm-forms&quot;]/app-project-list[1]/div[@class=&quot;container p-0&quot;]/article[@class=&quot;xm-table col-md-12 p-0&quot;]/app-table-xm[1]/div[@class=&quot;container p-0&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;table-responsive ng-star-inserted&quot;]/table[@class=&quot;table table-scroll-x table-hover&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/th[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-default ng-star-inserted&quot;]/span[1]/i[@class=&quot;material-icons xm-btn-editar&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='xm-main']/article[2]/app-project-list/div/article/app-table-xm/div/div/div[2]/table/tbody/tr[9]/th/div/button/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En trámite'])[6]/following::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[8]/following::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='textsms'])[9]/preceding::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sync_alt'])[9]/preceding::i[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/th/div/button/span/i</value>
   </webElementXpaths>
</WebElementEntity>
